In [1]:
import numpy as np

In [2]:
scores = np.array([
    [75,88,92,85],
    [66,70,65,60],
    [90,95,98,100],
    [50,45,60,55],
    [80,85,89,90]
])

In [3]:
min_scores = scores.min(axis=1,keepdims=True)
max_scores = scores.max(axis=1,keepdims=True)

normalized = (scores - min_scores) / (max_scores - min_scores + 1e-8)


print(normalized)


[[0.         0.76470588 1.         0.58823529]
 [0.6        1.         0.5        0.        ]
 [0.         0.5        0.8        1.        ]
 [0.33333333 0.         1.         0.66666667]
 [0.         0.5        0.9        1.        ]]


In [4]:
sensor_data = np.array([
    [100, 105, 98, 110, 95, 115, 102, 108, 99, 104],     # Sensor 1 (°C)
    [0.8, 0.85, 0.82, 0.9, 0.7, 0.95, 0.78, 0.88, 0.8, 0.83],  # Sensor 2 (V)
    [5000, 5200, 5100, 5300, 4900, 5400, 5050, 5150, 4950, 5250] # Sensor 3 (RPM)
])

In [5]:
min_vals = sensor_data.min(axis=1,keepdims=True)
max_vals = sensor_data.max(axis=1,keepdims=True)

normalized = (sensor_data - min_vals) / (max_vals - min_vals + 1e-8)

In [6]:
print(normalized)

[[0.25       0.5        0.15       0.75       0.         1.
  0.35       0.65       0.2        0.45      ]
 [0.39999998 0.59999998 0.47999998 0.79999997 0.         0.99999996
  0.31999999 0.71999997 0.39999998 0.51999998]
 [0.2        0.6        0.4        0.8        0.         1.
  0.3        0.5        0.1        0.7       ]]


In [7]:
import numpy as np

people = np.array([
    [25,60,170],
    [30,72,180],
    [22,55,160],
    [35,90,175]
])

In [ ]:
min_vals = people.min(axis=0)
max_vals = people.max(axis=0)


minmax_normalized = (people - min_vals) / (max_vals - min_vals)



In [8]:
returns = np.array([0.10,0.12,0.08])
weights = np.array([0.4,0.4,0.2])

In [9]:
cov_matrix = np.array([
    [0.04,0.006,0.012],
    [0.006,0.09,0.018],
    [0.012,0.018,0.0225]
])

In [10]:
expected_return = np.dot(weights,returns)

In [11]:
portfolio_variance = np.dot(weights.T,np.dot(cov_matrix,weights))


portfolio_std = np.sqrt(portfolio_variance)

In [12]:
print("Expected Return:", round(expected_return * 100, 2), "%")
print("Portfolio Risk (Std Dev):", round(portfolio_std * 100, 2), "%")

Expected Return: 10.4 %
Portfolio Risk (Std Dev): 16.86 %


In [13]:
prices = np.array([100,105,110,100])


In [15]:
simple_returns = (prices[1:] - prices[:-1]) / prices[:-1]
print('Simple Returns:',simple_returns)

Simple Returns: [ 0.05        0.04761905 -0.09090909]


In [18]:
log_returns = np.log(prices[1:] / prices[:-1])
print(log_returns)

[ 0.04879016  0.04652002 -0.09531018]


In [20]:
returns = np.array([0.05,0.1,0.02])
weights = np.array([0.5,0.3,0.2])

portfolio_return = np.dot(weights,returns)
print('Porfoli Return:',portfolio_return)

Porfoli Return: 0.059


In [21]:
returns = np.array([
    [0.01,0.03,0.005],
    [0.02,0.01,0.007],
    [-0.01,0.02,0.003],
    [0.005,-0.01,0.002]
])

mean_returns = np.mean(returns,axis=0)

In [23]:
cov_matrix = np.cov(returns.T)
print(cov_matrix)

[[ 1.56250000e-04 -2.08333333e-05  2.12500000e-05]
 [-2.08333333e-05  2.91666667e-04  1.58333333e-05]
 [ 2.12500000e-05  1.58333333e-05  4.91666667e-06]]


In [24]:
import numpy as np

arr = np.array([10,20,30,40,50])
mask = arr > 30
print(arr[mask])

[40 50]


In [25]:
arr = np.array([5,10,15,20,25])

mask = (arr >= 10) & (arr <= 20)

In [26]:
print(arr[mask])

[10 15 20]


In [27]:
arr = np.array([12,45,7,30])


new_arr = np.where(arr < 20,0,arr)

In [28]:
print(new_arr)

[ 0 45  0 30]


In [ ]:
mat  = np.array([[1,2,3]])